export enum ACTION_TYPES {
  ADD_COMMENT = "ADD_COMMENT",
  DELETE_COMMENT = "DELETE_COMMENT",
  EDIT_COMMENT = "EDIT_COMMENT",
  UPVOTE_COMMENT = "UPVOTE_COMMENT",
  DOWNVOTE_COMMENT = "DOWNVOTE_COMMENT",
  ADD_REPLY = "ADD_REPLY",
  DELETE_REPLY = "DELETE_REPLY",
  EDIT_REPLY = "EDIT_REPLY",
  UPVOTE_REPLY = "UPVOTE_REPLY",
  DOWNVOTE_REPLY = "DOWNVOTE_REPLY",
  SORT_COMMENTS = "SORT_COMMENTS"
}
